// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kukwohbpsydkskomlajz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1a3dvaGJwc3lka3Nrb21sYWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDYwODEsImV4cCI6MjA2NDg4MjA4MX0.TJugO3bV0haCpa5fdW2lDW0LTkJ5X82whRsDPYToA-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);